### ISSUE TITLE
Can't use flatpak-spawn from other partitions

### ISSUE THREAD

**Issue by VarLad** [flathub/dev.lapce.lapce#3]
Can't use flatpak-spawn in other partitions. 
Specifically, can't use flatpak-spawn when Lapce working folder is set to another partition. 
More specifically, I get, `Portal call failed: Failed to start command: Failed to change to directory "/run/flatpak/doc/(some number)/folder_name" (No such file or directory)`
The workaround is to 
1. Give permissions to your `/run/media/username` folder
2. Do the flatpak-spawn in your main partition, and `cd` to the partition folder. (surprisingly, it does work)

**Comment by fastrizwaan** [comment]
give full filesystem access using `sudo flatpak override --filesystem=host dev.lapce.lapce`
