### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by sebastian-de** [flathub/dev.lapce.lapce#41]
I created this Flatpak manifest for fun to get familiar with the Flatpak/Flathub ecosystem and to learn how to package a Rust application with it.

The basic building blocks are there and for a new release one basically has to click "merge" after the pipeline finishes.

But this Flatpak definitely needs some love to make it usable out of the box with more programming languages. Since I don't use Lapce myself I'm actually not much of help there.

Is someone willing to take over maintaining de.lapce.lapce?

**Comment by panekj** [comment]
Yes, I can maintain it and would like to make it an official installation option in future

**Comment by sebastian-de** [comment]
Nice, thanks!
I'll ask the Flathub team to give you the needed permissions.
Please let me know if you need any information from my side before you get started.
