### ISSUE TITLE
Last flatpak upgrade reset all the settings

### ISSUE THREAD

**Issue by ell1e** [flathub/dev.lapce.lapce#47]
I'm not sure if it's intended but since I'm guessing it might not be, for me the last flatpak upgrade that happened a few days ago to 0.2.8 reset all the settings for me. Particularly I had a different font set, and I had auto closing pairs disabled, and both of these were reset again (with default fonts being reapplied and auto closing pairs re-enabled). I managed to reapply these settings manually easily, so I don't think it reset because e.g. they somehow became unavailable, but rather there seems to have been issue migrating them properly. I'm on openSUSE Leap 15.5 using flatpak 1.14.4.

**Comment by panekj** [comment]
Release version wasn't baked which was fixed, nothing I can do about it.
