### ISSUE TITLE
LSP plugins should give error indication when they fail to run

### ISSUE THREAD

**Issue by ell1e** [flathub/dev.lapce.lapce#49]
The LSP plugins should give error indication when they fail to run. None of them work for python, most likely due to #32 I think, but instead of any obvious marker that the plugin encountered an error that I can click for more details instead there's just no autocomplete or diagnostics with zero explanation why.

**Comment by panekj** [comment]
Notifications were implemented in Lapce before but have to be reimplemented due to Floem change, but also this is not related to this repository, as this is not in scope of flatpak package.

**Comment by ell1e** [comment]
For what it's worth, before this UI toolkit change I don't think I saw this working either!
